server:
  port: 8083

eureka:
  instance:
    statusPageUrlPath: http://localhost:8083/api/auth/actuator/info
    healthCheckUrlPath: http://localhost:8083/api/auth/actuator/health
    metadataMap.zone: zone2
    hostname: localhost