server:
  port: 8080
logging:
  level:
    root: debug

spring:
  application:
    name: LOADBALANCER

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        zone1: http://localhost:8761/eureka/
        zone2: http://127.0.0.1:8762/eureka/
  instance:
    hostname: localhost
